#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-enrich
Version  : 1.2.7
Release  : 4
URL      : https://files.pythonhosted.org/packages/bb/77/cb9b3d6f2e2e5f8104e907ea4c4d575267238f52c51cf9f864b865a99710/enrich-1.2.7.tar.gz
Source0  : https://files.pythonhosted.org/packages/bb/77/cb9b3d6f2e2e5f8104e907ea4c4d575267238f52c51cf9f864b865a99710/enrich-1.2.7.tar.gz
Summary  : enrich
Group    : Development/Tools
License  : MIT
Requires: pypi-enrich-license = %{version}-%{release}
Requires: pypi-enrich-python = %{version}-%{release}
Requires: pypi-enrich-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(pip)
BuildRequires : pypi(py)
BuildRequires : pypi(rich)
BuildRequires : pypi(setuptools)
BuildRequires : pypi(setuptools_scm)
BuildRequires : pypi(setuptools_scm_git_archive)
BuildRequires : pypi(wheel)
BuildRequires : pypi-pluggy
BuildRequires : pypi-pytest
BuildRequires : pypi-tox
BuildRequires : pypi-virtualenv

%description
# enrich
Enriched extends [rich](https://pypi.org/project/rich/) library functionality
with a set of changes that were not accepted to rich itself.

%package license
Summary: license components for the pypi-enrich package.
Group: Default

%description license
license components for the pypi-enrich package.


%package python
Summary: python components for the pypi-enrich package.
Group: Default
Requires: pypi-enrich-python3 = %{version}-%{release}

%description python
python components for the pypi-enrich package.


%package python3
Summary: python3 components for the pypi-enrich package.
Group: Default
Requires: python3-core
Provides: pypi(enrich)
Requires: pypi(rich)

%description python3
python3 components for the pypi-enrich package.


%prep
%setup -q -n enrich-1.2.7
cd %{_builddir}/enrich-1.2.7

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1642004369
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 -m build --wheel --skip-dependency-check --no-isolation

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-enrich
cp %{_builddir}/enrich-1.2.7/LICENSE %{buildroot}/usr/share/package-licenses/pypi-enrich/ae0ea9d8439d6e6da94de842ab8e328a7fdad00e
pip install --root=%{buildroot} --no-deps --ignore-installed dist/*.whl
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-enrich/ae0ea9d8439d6e6da94de842ab8e328a7fdad00e

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
